# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NBtesting',
                'doc_host': 'https://lidar532.github.io',
                'git_url': 'https://github.com/lidar532/NBtesting',
                'lib_path': 'NBtesting'},
  'syms': { 'NBtesting.testlib': { 'NBtesting.testlib.test_a': ('testlib.html#test_a', 'NBtesting/testlib.py'),
                                   'NBtesting.testlib.test_b': ('testlib.html#test_b', 'NBtesting/testlib.py'),
                                   'NBtesting.testlib.test_widget': ('testlib.html#test_widget', 'NBtesting/testlib.py')},
            'NBtesting.testlib2': { 'NBtesting.testlib2.test_lib2_a': ('testlib2.html#test_lib2_a', 'NBtesting/testlib2.py'),
                                    'NBtesting.testlib2.test_lib2_b': ('testlib2.html#test_lib2_b', 'NBtesting/testlib2.py')},
            'NBtesting.widgets': {'NBtesting.widgets.FolderSelector': ('widgets.html#folderselector', 'NBtesting/widgets.py')}}}
