# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NBtesting',
                'doc_host': 'https://lidar532.github.io',
                'git_url': 'https://github.com/lidar532/NBtesting',
                'lib_path': 'NBtesting'},
  'syms': {'NBtesting.core': {'NBtesting.core.foo': ('core.html#foo', 'NBtesting/core.py')}}}
