# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_testlib2.ipynb.

# %% auto 0
__all__ = ['test_lib2_a', 'test_lib2_b']

# %% ../nbs/10_testlib2.ipynb 5
def test_lib2_a( 
  value='Nothing' # A simple string
) -> str:         # the input value
  return f'test_lib2_a( {value})'

# %% ../nbs/10_testlib2.ipynb 6
def test_lib2_b(value = 'no value'):
  return f'test_lib2_b( {value} )'
